from building import *
Import('rtconfig')

cwd     = GetCurrentDir()
src	= Glob('*.c')
path = [cwd]

group = DefineGroup('nRF24L01', src, depend = ['PKG_USING_NRF24L01_DEMO'], CPPPATH = path)

Return('group')